kumuluzee:
  name: items-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  datasources:
    - jndi-name: jdbc/ItemsDB
      connection-url: jdbc:postgresql://localhost:5432/items
      username: dbuser
      password: postgres
rest-properties:
  maintenance-mode: false