kumuluzee:
  name: items-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8080
    http:
      port: 8080
  discovery:
    consul:
      hosts: http://localhost:8500
    ttl: 30
    ping-interval: 5
  datasources:
    - jndi-name: jdbc/ItemsDB
      connection-url: jdbc:postgresql://localhost:5432/items
      username: dbuser
      password: postgres
  health:
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/ItemsDB
    metrics:
      web-instrumentation:
        - name: items-endpoint
          url-pattern: /v1/items/*
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
                            <Configuration name="comments">
                                <Appenders>
                                    <Console name="console" target="SYSTEM_OUT">
                                        <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                                    </Console>
                                    <Socket name="logstash" host="8ff6c166-5030-437c-b97b-37178a04750d-ls.logit.io"
                                    port="24755" protocol="udp">
                                        <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                                    </Socket>
                                </Appenders>
                                <Loggers>
                                    <!-- Default logger -->
                                    <Root level="all">
                                        <AppenderRef ref="console" level="info" />
                                        <AppenderRef ref="logstash" level="trace" />
                                    </Root>
                                </Loggers>
                            </Configuration>'
rest-properties:
  maintenance-mode: false
  broken: false